easy_admin:
    site_name: 'DeepDict'
    entities:
        Faq:
            class : App\Entity\Faq
            controller: App\Controller\Admin\FaqController
    design:
        brand_color: '#1784c7'
        menu:
                    - { label: 'Dashboard', route: 'admin_dashboard', default: true }
                    - { label: 'Faq synchronization', route: 'faq_synchronization', default: true }
                    - { entity: 'Faq', label: 'Faq', icon: '' }