easy_admin:
    site_name: 'DeepDict'
    entities:
        Faq:
            class : App\Entity\Faq
            controller: App\Controller\Admin\FaqController
        KnowledgeBase:
            class : App\Entity\KnowledgeBase
            controller: App\Controller\Admin\KnowledgeBaseController
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-9', label: 'Basic information' }
                    - category
                    - { type: 'section', label: 'Optional' }
                    - title
                    - { property: 'content', type: 'textarea', css_class: 'js-markdown-input' }
        Category:
            class: App\Entity\Category
    design:
        brand_color: '#1784c7'
        menu:
                    - { label: 'Dashboard', route: 'admin_dashboard', default: true }
                    - { label: 'Knowledge Base', route: 'admin_knowledgebase', default: true }
                    -
                      label: 'Synchronization'
                      children:
                        - { label: 'Faq synchronization', route: 'faq_synchronization', default: true }
                    - { entity: 'Faq', label: 'Faq', icon: '' }
                    - { entity: 'KnowledgeBase', label: 'KnowledgeBase', icon: '' }
                    - { entity: 'Category', label: 'Category', icon: '' }
        assets:
            css:
                - 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css'
            js:
                - 'ckeditor/ckeditor.js'
                - 'ckeditor/init.js'