INSERT INTO deepdict.category (name) VALUES ('MySql');
INSERT INTO deepdict.category (name) VALUES ('PHP');
INSERT INTO deepdict.category (name) VALUES ('Git/GitLab');
INSERT INTO deepdict.category (name) VALUES ('Js');
INSERT INTO deepdict.category (name) VALUES ('PHPUnit');
INSERT INTO deepdict.category (name) VALUES ('JsPlugins');
INSERT INTO deepdict.category (name) VALUES ('XML');
INSERT INTO deepdict.category (name) VALUES ('PHPStorm');
INSERT INTO deepdict.category (name) VALUES ('Composer');